#%RAML 1.0
 |
    These constraints apply to *all* resources.

    *Note*: Autentication is validated before anything else in the request.

    Preconditions:
    - Requester is authenticated.
    - Request is authorized.

    Failures:
    - Requester is *not* authenticated.
      - Response code: 401
      - Rationale: Requester should be notified that he/she/it needs to log-in.
          There is no security risk in it.
    - Request is *not* authorized.
      - Response code: 404
      - Rationale: Requester should *not* be notified with response 403 that
          object exists but requester is not authorized.
          To malicious requester it reveals which objects exist.
