#%RAML 1.0 Library
usage: Used to specify basic API tests

annotationTypes:
  tests:
    description: |
      Note: Same description is used for both `object` and `array`.
      If returned type is `array` all elements must conform to spec.
    allowedTargets: Response
    type: Test[]

types:
  Test:
    additionalProperties: false
    properties:
      request?: TestRequest
      response: TestResponse
  TestRequest:
    additionalProperties: false
    properties:
      urlArgs?: TestUrlArgs[]
      header?: TestHeaderItems[]
      body?: TestRequestBodyItems[]
  TestUrlArgs:
    additionalProperties: false
    properties:
      name: string
      value: string
  TestResponse:
    additionalProperties: false
    properties:
      header?: TestHeaderItems[]
      body: TestResponseBodyItems[]
  TestHeaderItems:
    additionalProperties: false
    properties:
      name:
      value:
  TestRequestBodyItems:
    additionalProperties: false
    properties:
      name:
      value: any
  TestResponseBodyItems:
    additionalProperties: false
    properties:
      name:
      type:
      value?: any
