#%RAML 1.0
title: Semaphore
version: v2
baseUri: https://api.semaphoreci.com/v2
mediaType: application/json

types: !include types.raml
traits: !include traits.raml

# Top level resources

/users:
  displayName: "Users"

/teams:
  displayName: "Teams"

/projects:
  displayName: "Projects"

/shared_configs:
  displayName: "Shared Configurations"

/env_vars:
  displayName: "Environment Variables"

/config_files:
  displayName: "Configuration Files"

# Routes

/orgs:
  get:
    displayName: List your organizations
    is: [withResponseItems: {item : Org}]

  /{username}:
    get:
      displayName: Get an organization
      is: [withResponseItem: {item : Org}, withNotFoundError]

  /{org_username}:
    /teams:
      get:
        displayName: List teams in an organization
        is: [withResponseItems: {item : Team}]
      post:
        displayName: Create a team in an organization
        is: [withRequestItem: {item : TeamPost},
             withResponseItem: {item : Team},
             withNotFoundError,
             withPreconditionFailedError]
    /projects:
      get:
        displayName: List projects in an organization
        is: [withResponseItems: {item : Project}]

    /shared_configs:
      get:
        displayName: List shared configurations in an organization
        is: [withResponseItems: {item : SharedConfig}]
      post:
        displayName: Create shared configuration in an organization
        is: [withRequestItem: {item : SharedConfigPost},
            withResponseItem: {item : SharedConfig},
            withNotFoundError,
            withPreconditionFailedError]
    /users:
      get:
        displayName: List all users for a organization
        is: [withResponseItems: {item : User}, withNotFoundError]

/teams:
  /{id}:
    get:
      displayName: Get a team
      is: [withResponseItem: {item : Team}, withNotFoundError]
    delete:
      displayName: Delete a team
      is: [withNoBodyResponse, withNotFoundError]
    patch:
      displayName: Update a team
      is: [withRequestItem: {item : TeamPatch}, withResponseItem: {item : Team}, withNotFoundError]

  /{team_id}:
    /shared_configs:
      get:
        displayName: List shared configurations in a team
        is: [withResponseItems: {item : SharedConfig}, withNotFoundError]

      /{shared_config_id}:
        post:
          displayName: Add a shared configuration to a team
          is: [withNoBodyResponse, withNotFoundError]
        delete:
          displayName: Remove shared configuration from a team
          is: [withNoBodyResponse, withNotFoundError]

    /users:
      get:
        displayName: List members of a team
        is: [withResponseItems: {item : User}, withNotFoundError]
      /{username}:
        post:
          displayName: Add user to a team
          is: [withNoBodyResponse, withNotFoundError]
        delete:
          displayName: Remove user from a team
          is: [withNoBodyResponse, withNotFoundError]

    /projects:
      get:
        displayName: List project added to a team
        is: [withResponseItems: {item : Project}, withNotFoundError]

      /{project_id}:
        post:
          displayName: Add project to a team
          is: [withNoBodyResponse, withNotFoundError]
        delete:
          displayName: Remove project from a team
          is: [withNoBodyResponse, withNotFoundError]

/projects:
  /{project_id}:
    /shared_configs:
      get:
        displayName: List shared configurations attached to a project
        is: [withResponseItems: {item : SharedConfig}, withNotFoundError]

      /{shared_config_id}:
        post:
          displayName: Attach a shared configuration to a project
          is: [withResponseItem: {item : SharedConfig}, withNotFoundError]
        delete:
          displayName: Dettach a shared configuration from a project
          is: [withNoBodyResponse, withNotFoundError]

    /env_vars:
      get:
        displayName: List environment variables connected to a project
        is: [withResponseItems: {item : EnvVar}, withNotFoundError]
      /{env_var_id}:
        post:
          displayName: Connect a shared environment variable to a project
          is: [withNoBodyResponse, withNotFoundError]
        delete:
          displayName: Dissconnect a shared environment variable from a project
          is: [withNoBodyResponse, withNotFoundError]

    /config_files:
      get:
        displayName: List config files connected to a project
        is: [withResponseItems: {item : ConfigFile}, withNotFoundError]
      /{config_file_id}:
        post:
          displayName: Connect a shared config file to a project
          is: [withNoBodyResponse, withNotFoundError]
        delete:
          displayName: Dissconnect a shared config file from a project
          is: [withNoBodyResponse, withNotFoundError]

    /users:
      get:
        displayName: List all users fo a project
        is: [withResponseItems: {item : User}, withNotFoundError]

/shared_configs:
  /{id}:
    get:
      displayName: Get a shared configuration
      is: [withResponseItem: {item : SharedConfig}, withNotFoundError]
    delete:
      displayName: Delete a shared configuration
      is: [withNoBodyResponse, withNotFoundError]
    patch:
      displayName: Update a shared configuration
      is: [withRequestItem: {item : SharedConfigPatch},
          withResponseItem: {item : SharedConfig}, withNotFoundError]

  /{shared_config_id}:
    /env_vars:
      get:
        displayName: List environment variables belonging to a shared configuration
        is: [withResponseItems: {item : EnvVar}, withNotFoundError]
      post:
        displayName: Create environment variable within a shared configuration
        is: [withRequestItem: {item : EnvVarPost},
            withResponseItem: {item : EnvVar}, withNotFoundError]
    /config_files:
      get:
        displayName: List config files belonging to a shared configuration
        is: [withResponseItems: {item : ConfigFile}, withNotFoundError]
      post:
        displayName: Create a config file within a shared configuration
        is: [withRequestItem: {item : ConfigFilePost},
            withResponseItem: {item : ConfigFile}, withNotFoundError]

/env_vars:
  /{id}:
    get:
      displayName: Get an environment variable
      is: [withResponseItem: {item : EnvVar}, withNotFoundError]
    delete:
      displayName: Delete an environment variable
      is: [withNoBodyResponse, withNotFoundError]
    patch:
      displayName: Update an environment variable
      is: [withRequestItem: {item : EnvVarPatch},
          withResponseItem: {item : EnvVar}, withNotFoundError]

/config_files:
  /{id}:
    get:
      displayName: Get a config file
      is: [withResponseItem: {item : ConfigFile}, withNotFoundError]
    delete:
      displayName: Delete a config file
      is: [withNoBodyResponse, withNotFoundError]
    patch:
      displayName: Update a config file
      is: [withRequestItem: {item : ConfigFilePatch},
          withResponseItem: {item : ConfigFile}, withNotFoundError]
