/orgs:
  displayName: "Organizations"

/orgs:
  get:
    description: List your organizations
    is: [withResponseItems: {item : Org}]

  /{username}:
    get:
      description: Get an organization
      is: [withResponseItem: {item : Org}, withNotFoundError]
