#!/usr/bin/env node

var raml2obj = require('raml2obj');
var fs = require('fs');
var output_path = "api.json";

raml2obj.parse("raml/api.raml").then((ramlObj) => {
  var json_output = JSON.stringify(ramlObj);
  fs.writeFile(output_path, json_output);
});

console.log("Saved api specification to: " + output_path);
