#!/usr/bin/env bash

node scripts/output-json.js

rm -rf doc/entity-view

bundle exec raml_visualizer "json-output.json" "doc/entity-view" "templates" "html"

export CSS_LINK='<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">'

for file in doc/entity-view/{,**/}*.html; do
  echo $CSS_LINK >> ${file}
done

rm -f json-output.json
