#!/usr/bin/env bash

node scripts/output-json.js

rm -rf doc/entity-view

bundle exec raml_visualizer "json-output.json" "entity-view" "templates" "html" "stylesheets"

mv entity-view/ doc

rm -f json-output.json
