#!/usr/bin/env bash
set -euo pipefail

if [ -z $S3_BUCKET_NAME ]; then
  echo "Please export the S3_BUCKET_NAME variable and try again."
  exit 1
fi

if [ ! -f api.json ]; then
  echo "api.json file not found"
  exit 1
fi

spec_file=api_specification_$(date +%b_%d_%Y_%H_%M_%S).json
s3_path="s3://$S3_BUCKET_NAME/$spec_file"

cp api.json $spec_file

aws s3 cp $spec_file $s3_path --acl=public-read

rm -rf $spec_file

echo "Api specification published"
echo "$s3_path"
